[package]
name = "libcstt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcst = { git = "https://github.com/Instagram/LibCST"}