[package]
name = "little_exif"
version = "0.1.0"
edition = "2021"


[dependencies]
little_exif = "0.6.20"
walkdir = "2.5.0"


[profile.release]
overflow-checks = true
panic = "abort"
debug = true
debug-assertions = true

